import { writeFileSync, chmodSync, readdirSync, rmSync, statSync } from 'node:fs'
import { execFile, execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { paths, warpLaunchDir } from './paths.mjs'
import { ensureDir, logLine } from './util.mjs'

export const TERMINALS = ['warp', 'terminal.app', 'custom']

const shellQuote = (value) => `'${String(value).replace(/'/g, `'\\''`)}'`
const yamlQuote = (value) => `'${String(value).replace(/'/g, `''`)}'`

// Everything a terminal needs to run is baked into one launcher script, so no
// terminal adapter ever has to escape the message text or the claude command.
export const writeLauncher = (sessionId, cwd, command) => {
  const file = join(paths.sessionDir(sessionId), 'resume.sh')
  ensureDir(paths.sessionDir(sessionId))
  const script = [
    '#!/usr/bin/env bash',
    '# generated by buzz-wake, safe to delete',
    `cd ${shellQuote(cwd)} || exit 1`,
    // The window must belong to the profile that opened it: its own key, its own
    // spool. Hardcoding the default home sourced the wrong env, which signed one
    // agent's reply with another agent's key. Exporting the home also makes the
    // hooks in the resumed session register back into this profile.
    `export BUZZWAKE_HOME=${shellQuote(paths.home)}`,
    `[ -f ${shellQuote(paths.env)} ] && . ${shellQuote(paths.env)}`,
    command,
    '',
  ].join('\n')
  writeFileSync(file, script)
  chmodSync(file, 0o700)
  return file
}

const sweepWarpConfigs = () => {
  try {
    for (const name of readdirSync(warpLaunchDir)) {
      if (!name.startsWith('buzzwake-')) continue
      const file = join(warpLaunchDir, name)
      if (Date.now() - statSync(file).mtimeMs > 60_000) rmSync(file, { force: true })
    }
  } catch {
    // launch dir may not exist yet
  }
}

const launchWarp = (sessionId, cwd, launcher, title) => {
  ensureDir(warpLaunchDir)
  sweepWarpConfigs()
  const name = `buzzwake-${sessionId}`
  const file = join(warpLaunchDir, `${name}.yaml`)
  const yaml = [
    '---',
    `name: ${yamlQuote(name)}`,
    'windows:',
    '  - tabs:',
    `      - title: ${yamlQuote(title)}`,
    '        layout:',
    `          cwd: ${yamlQuote(cwd)}`,
    '          commands:',
    `            - exec: ${yamlQuote(launcher)}`,
    '',
  ].join('\n')
  writeFileSync(file, yaml)
  execFileSync('/usr/bin/open', [`warp://launch/${name}`])
  // Warp reads the file on open; drop it shortly after so the launch list stays clean.
  setTimeout(() => rmSync(file, { force: true }), 15_000).unref?.()
  return { terminal: 'warp', config: file }
}

const launchTerminalApp = (launcher) => {
  const script = `tell application "Terminal"
  activate
  do script ${JSON.stringify(launcher)}
end tell`
  execFileSync('/usr/bin/osascript', ['-e', script])
  return { terminal: 'terminal.app' }
}

const launchCustom = (template, cwd, launcher) => {
  const command = template.replaceAll('{{cwd}}', cwd).replaceAll('{{cmd}}', launcher)
  execFile('/bin/sh', ['-c', command], (error) => {
    if (error) logLine(paths.routerLog, `[terminal] custom launch failed: ${error.message}`)
  })
  return { terminal: 'custom', command }
}

export const openTerminal = ({ terminal, sessionId, cwd, launcher, title, customTemplate }) => {
  if (terminal === 'terminal.app') return launchTerminalApp(launcher)
  if (terminal === 'custom') {
    if (!customTemplate) throw new Error('resume.terminal=custom 需要配置 launch_template')
    return launchCustom(customTemplate, cwd, launcher)
  }
  return launchWarp(sessionId, cwd, launcher, title)
}

export const terminalAvailable = (terminal) => {
  if (terminal === 'warp') {
    try {
      statSync('/Applications/Warp.app')
      return true
    } catch {
      return false
    }
  }
  if (terminal === 'terminal.app') return true
  return true
}

// Absent key means unlocked. Detection failures fall through to "unlocked" so
// a broken probe can never silently disable resume forever.
export const screenIsLocked = () => {
  try {
    const raw = execFileSync('/bin/sh', [
      '-c',
      "/usr/sbin/ioreg -n Root -d1 -a | /usr/bin/plutil -extract IOConsoleUsers.0.CGSSessionScreenIsLocked raw - 2>/dev/null",
    ], { encoding: 'utf8' }).trim()
    return raw === 'true' || raw === '1'
  } catch {
    return false
  }
}
